#!/usr/bin/env python
import os
import sys
import math
import argparse
import subprocess

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = "\033[1m"

    def disable(self):
        self.HEADER = ''
        self.OKBLUE = ''
        self.OKGREEN = ''
        self.WARNING = ''
        self.FAIL = ''
        self.ENDC = ''
        
def header1(text):
	rows, columns = os.popen('stty size', 'r').read().split()
	
	divider = "+"
	for i in range(int(columns)-2):
		divider += "-"
	divider += "+"
	padding = ""
	paddinglen = (float(columns)-(2+len(text)))
	extrapad = ""
	if paddinglen % 2:
		extrapad = " "
	for i in range(int(paddinglen/2)):
		padding += " "
	print bcolors.OKGREEN + divider
	print "|" + padding + extrapad + text + padding + "|"
	print divider + bcolors.ENDC

def header2(text):
	print
	print bcolors.BOLD + bcolors.OKGREEN + "==[ " + text + " ]==" + bcolors.ENDC
	
def step(text):
	print bcolors.OKBLUE + "[...] " + text + bcolors.ENDC
	
def run(cmd, message):
	proc = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	stdout, stderr = proc.communicate()
	if proc.returncode:
		print bcolors.FAIL + "Failed to run command {0}, exit status {1}! Below is the output:".format(cmd, proc.returncode) + bcolors.ENDC
		print stdout
		print stderr
		print bcolors.FAIL + message + bcolors.ENDC
	return proc.returncode

# Check args
parser = argparse.ArgumentParser()
parser.add_argument('--update', const=True, default=False, action='store_const', help="Update all goinstalled packages before the build process. Might be helpful if you are getting build errors.")
parser.add_argument('--clean', const=True, default=False, action='store_const', help="Rather than building, clean all files from the build. Comparable to running make clean for the framework and each module.")

args = parser.parse_args()

# First, install everything required
step("Fetching required packages with goinstall")

f = open('framework/src/goinstalls')
for line in f:
	cmd = "goinstall"
	if args.update:
		cmd += " -u"
	if run(cmd+' '+line, "Failed to goinstall package!"):
		sys.exit(1)


os.chdir('framework/src')

if args.clean:
	step("Cleaning existing framework pacakges and commands")
	if run('gomake clean', 'Cleaning existing packages failed!'):
		print "Continuing happily..."

# Next, compile framework packages and commands
step("Compiling framework packages and commands")

if run('gomake', "Build failed :("):
	sys.exit(1)

os.chdir('../..')

# Finally, compile the actual modules
step("Compiling modules")

wfdrcmd = 'compile'
if args.clean:
	wfdrcmd = 'recompile'

if run('wfdr '+wfdrcmd+' all', "Attempting to "+wfdrcmd+" modules failed"):
	sys.exit(1)
	#print "Because it might be a module you don't care about, we're continuing happily :)"
	#print "Although you might want to look into the issue..."


header2("DONE!")
print "Framework has been built! To run it, start the daemon in one terminal using wfdr-deamon [sic], and then control modules using the wfdr command."
print "wfdr start <modulename> starts a module, wfdr stop <modulename> stops, etc. Run wfdr with no arguments to see usage."