#!/bin/bash

destdir=`dirname $WFDR_DEST`

mkdir -p $destdir


if [ -f $WFDR_SOURCE_1 ]; then
	sources=$WFDR_SOURCE_1
fi

if [ -f $WFDR_SOURCE_2 ]; then
	sources=$sources" "$WFDR_SOURCE_2
fi

#echo $sources
if [ "$WFDR_CONTEXT" = "prod" ]; then
	cat $sources | css-varfinder global.txt | css-minifier > $WFDR_DEST
else
	cat $sources | css-varfinder global.txt > $WFDR_DEST
fi