#!/bin/bash

if [ -f $WFDR_SOURCE_2 ]; then
	cat $WFDR_SOURCE_2 > $WFDR_DEST
elif [ -f $WFDR_SOURCE_1 ]
	cat $WFDR_SOURCE_1 > $WFDR_DEST
else
	echo "Fatal error: Neither source 1 ($WFDR_SOURCE_1) or source 2 ($WFDR_SOURCE_2) exist."
	exit 1
fi
