#!/bin/bash
# Installs the framework, assuming that the current directory is a git repository.

#/home/server/Dropbox/web is the assumed path. Note that the location can be on a remote server, rsync is used to copy the files.
installdir=/home/server/Dropbox/web

git pull

if ./compile; then
	echo "Built framework, installing..."
else
	echo "Compiling framework and modules failed, aborting!"
	exit 1
fi

if rsync -a . "$installdir"; then
	cwd=`pwd`
	cd $installdir
	modnamesspecified=0
	for i in $@; do
		wfdr recompile $i
		wfdr restart $i
		modnamesspecified=1
	done
	cd $cwd
	echo "Changes installed."
	if [ !$modnamesspecified ]; then
		echo "If there were source file changes, you will now have to cd to $installdir and"
		echo "wfdr recompile <modulename>"
		echo "wfdr restart <moudulename>"
		echo "However, if there were simple css/js changes, and you are deploying to a computer that supports inotify, then you should not have to restart the modules for the changes to take effect."
	fi
else
	echo "Installing to $installdir failed. Make sure that the folder exists, your syntax is correct, and you have permission to write to the folder."
fi