#!/bin/bash

destdir=`dirname $WFDR_DEST`

mkdir -p $destdir


if [ -f $WFDR_SOURCE_1 ]; then
	sources=$WFDR_SOURCE_1
fi

if [ -f $WFDR_SOURCE_2 ]; then
	sources=$sources" "$WFDR_SOURCE_2
fi

#echo $sources
cat $sources | varfinder global.txt | minifier > $WFDR_DEST