#!/bin/bash

destdir=`dirname $WFDR_DEST`

mkdir -p $destdir

if [ -f $WFDR_SOURCE_1 ]; then
	cat $WFDR_SOURCE_1 > $WFDR_DEST
	exit
fi

if [ -f $WFDR_SOURCE_2 ]; then
	cat $WFDR_SOURCE_2 > $WFDR_DEST
	exit
fi